### ISSUE TITLE
Typo at line 178 in Application.coffee

### ISSUE THREAD

**Issue by chartotu19** [umd-mith/mithgrid#38]
It should be cconfig as the function parameter. 
https://github.com/umd-mith/mithgrid/blob/master/src/application.coffee#L178

**Comment by jgsmith** [comment]
It does look like that. Go ahead and create a pull request with a fix and I'll merge it.

**Comment by jgsmith** [comment]
I went ahead and edited the file through the github interface. That was easier than creating a new dev clone.
